name: .NET

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      WORKDIR: ./src/HelloWorld
      CONFIG: Release
      AZURE_FUNCTIONAPP_NAME: HelloWorld-Marco
    defaults:
      run:
        working-directory: ${{env.WORKDIR}}

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Build and Test a project
      uses: CloudRepublic/githubactions-workshop/.github/actions/rbt@main
      with:
        working-directory: ${{env.WORKDIR}}
        config: ${{env.CONFIG}}

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{env.WORKDIR}}/bin/Release/net6.0/publish/
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

