name: 'Restore Build and Test'
description: 'Restore build and test a project'
inputs:
  docker-username:
    description: 'Dockerhub username'
    required: true

runs:
  using: "composite"
  steps:

  - run: |
      echo "tag=${{ inputs.docker-image-version }}-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
    shell: bash
    working-directory: ${{ inputs.working-directory }}
