name: .NET

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WORKDIR: ./src/HelloWorld
      CONFIG: Release
      AZURE_FUNCTIONAPP_NAME: HelloWorld-Marco
    defaults:
      run:
        working-directory: ${{env.WORKDIR}}

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Build
        run: dotnet build --no-restore --output ./output
        shell: bash

      - name: Test
        working-directory: ${{ env.WORKDIR }}.UnitTests
        run: |
          dotnet test --configuration ${{ env.CONFIG }}
        shell: bash

      - name: Publish
        run: |
          dotnet publish -c ${{ env.CONFIG }}
        shell: bash

      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{env.WORKDIR}}/bin/Release/net6.0/publish/
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
